#!/usr/bin/env bash
# Author: github.com/danielhoherd
# License: Unlicense

readonly IMAGE="$1"
shift

usage() {
  cat <<EOF
Run a throwaway docker container with optional image and commands.

${0##*/} [docker-image [command]]
EOF
}

[ "${IMAGE}" == "--help" ] || [ "${IMAGE}" == "-h" ] && { usage ; exit 1 ; }

# shellcheck disable=SC2140
docker run --rm -t -i --mount type=bind,src="$PWD",dst="/docker-share" "${IMAGE:-danielhoherd/uw}" "${@:-bash}"
