#!/usr/bin/env bash
# Author: github.com/danielhoherd
# License: MIT

usage() {
  cat <<EOF
Description: Run a throwaway docker container with optional image and commands.

Usage: ${0##*/} -h | [-x] [-i <docker-image>] [command]
EOF
}

while getopts :i:xh option ; do
  case "${option}" in
    i) export IMAGE="${OPTARG}" ;;
    x) set -x ;;
    h|*) usage ; exit 1 ;;
  esac
done
shift $((OPTIND - 1))

# shellcheck disable=SC2140
docker run --rm --interactive --tty --workdir="/docker-share" --mount "type=bind,src=$PWD,dst=/docker-share" "${IMAGE:-quay.io/danielhoherd/lw:debian}" "${@:-bash}"
