#!/usr/bin/env bash
# Author: github.com/danielhoherd
# License: Unlicense
# Formats `docker images` in a vertical style similar to mysql's \G

# https://docs.docker.com/engine/reference/commandline/images/#formatting

docker images --format="{{.Repository}}:{{.Tag}}
    .ID:            {{.ID}}
    .Repository:    {{.Repository}}
    .Tag:           {{.Tag}}
    .Digest:        {{.Digest}}
    .CreatedSince:  {{.CreatedSince}}
    .CreatedAt:     {{.CreatedAt}}
    .Size:          {{.Size}}" "$@"
