#!/usr/bin/env bash
# Author: github.com/danielhoherd
# License: Unlicense

usage() {
  cat <<EOF
Description: Run a throwaway docker container with optional image and commands.

Usage: ${0##*/} -h | [-x] [docker-image [command]]
EOF
}

while getopts :xh option ; do
  case "${option}" in
    x) set -x ;;
    h|*) usage ; exit 1 ;;
  esac
done
shift $((OPTIND - 1))

readonly IMAGE="$1"
shift

# shellcheck disable=SC2140
docker run --rm -t -i --mount type=bind,src="$PWD",dst="/docker-share" "${IMAGE:-danielhoherd/uw}" "${@:-bash}"
