#!/usr/bin/env bash
# Author: github.com/danielhoherd
# License: MIT
# Purpose: Apple Music.app controller cli

command -v osascript &>/dev/null || { echo "osascript is required, are you using OS X?" >&2 ; exit 1 ; }

function script_usage {
  cat <<EOF
Usage: ${0##*/} <verb>

Verbs:
  pl (play)
  pa (pause)
  pp (playpause)
  st (stop)
  n (next)
  pr (previous)
  vu (volup)
  vd (voldown)
  setvol [0-100]
  getvol
  mute
  unmute
  rate [0-5]
  open
  quit
  restart
EOF
}

if [[ $# -lt 1 ]] ; then
  script_usage ;
  exit ;
fi

play='tell application "Music" to play'
pause='tell application "Music" to pause'
playpause='tell application "Music" to playpause'
stop='tell application "Music" to stop'
next='tell application "Music" to next track'
prev='tell application "Music" to previous track'
rate="tell application \"Music\" to set rating of current track to $(( ${2:-0} * 20 ))"
get_rating='tell application "Music" to get rating of current track'
title='tell application "Music" to name of current track as string'
volup='tell application "Music" to set sound volume to sound volume + 5'
voldown='tell application "Music" to set sound volume to sound volume - 5'
setvol="tell application \"Music\" to set sound volume to $2"
getvol='tell application "Music" to get sound volume as integer'
unmute='tell application "Music" to set mute to false'
mute='tell application "Music" to set mute to true'
quit='tell application "Music" to quit'

case "$1" in
  play | pl )
    osascript -e "${play}"
  ;;

  pause | pa )
    osascript -e "${pause}"
  ;;

  playpause | pp )
    osascript -e "${playpause}"
  ;;

  stop | st )
    osascript -e "${stop}"
  ;;

  next | n )
    osascript -e "${next}"
  ;;

  prev | pr )
    osascript -e "${prev}"
  ;;

  setvol )
    osascript -e "${setvol}"
  ;;

  getvol )
    osascript -e "${getvol}"
  ;;

  mute )
    osascript -e "${mute}"
  ;;

  unmute )
    osascript -e "${unmute}"
  ;;

  title )
    osascript -e "${title}"
  ;;

  volup | vu )
    osascript -e "${volup}"
  ;;

  voldown | vd )
    osascript -e "${voldown}"
  ;;

  rate )
    if [[ $# -ne 2 ]] ; then
      rating=$(osascript -e "${get_rating}")
      echo "$(( rating / 20 ))"
    else
      osascript -e "${rate}"
    fi
  ;;

  restart )
    if pgrep -u "$USER" -qxl Music ; then
      osascript -e "${quit}"
      sleep 10
      pkill Music
      pkill -9 Music
      sleep 1
      open -a Music
    else
      echo "Music is not running"
      exit 1
    fi
  ;;

  open )
    open -a Music
  ;;

  quit )
    osascript -e "${quit}"
  ;;

  * )
    script_usage
  ;;

esac
