#!/usr/bin/env bash
# Author: github.com/danielhoherd
# License: MIT
# Purpose: Spawn a new container and drop into a shell

usage(){ cat <<EOF
Launches a k8s pod with an optional docker container given.

    -h  Print help
    -d  Dry run and print output spec
    -N  Specify a node
    -n  Namespace
    -x  Enable xtrace

${0##*/} [-h] | [-x] [-d] [-n namespace] [-N k8s-nodename] [-i docker-image] [command]
EOF
}

extra_args=()
dry_or_interactive=( -t -i --rm '--restart=Never' )

while getopts ':i:hxdn:N:' option ; do
  case "${option}"
  in
  x) set -x ;;
  d) dry_or_interactive=( '--dry-run=client' -o yaml '--restart=OnFailure' ) ;;
  i) IMAGE="$OPTARG" ;;
  n) extra_args+=( --namespace "$OPTARG" ) ;;
  N) node="$OPTARG" ;;
  h|*) usage ; exit 1 ;
  esac
done
shift $((OPTIND - 1))

epochtime="$(date +%s)"

if [ -n "$node" ] ; then
  extra_args+=( '--overrides={ "spec": { "nodeSelector": { "kubernetes.io/hostname": "'"$node"'" } } }'  )
fi

kubectl run "${extra_args[@]}" "${dry_or_interactive[@]}" "${USER//./-}-test-${epochtime}" --image="${IMAGE:-quay.io/danielhoherd/uw}" "${@:-bash}"
