# https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html
# https://www.python.org/dev/peps/pep-0518/#file-format
[tool.black]
exclude = '(venv|.vscode)'
include = '\.pyi?$'
line-length = 132
#skip-string-normalization = true
target-version = ['py310']

[tool.ruff]
fixable = ["ALL"]
select = ["E", "F", "Q", "S"]
ignore = ["E501", "S311", "S603"]
