# https://www.python.org/dev/peps/pep-0518/#file-format

# https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html
[tool.black]
exclude = '(venv|.vscode)'
include = '\.pyi?$'
line-length = 132
#skip-string-normalization = true
target-version = ['py310']

[tool.ruff.lint]
fixable = ["ALL"]

# https://docs.astral.sh/ruff/rules/
select = [
  "ASYNC",
  "BLE",
  "C",
  "E",
  "F",
  "FLY",
  "FURB",
  "I",
  "N",
  "PERF",
  "Q",
  "R",
  "RUF",
  "S",
  "UP",
  "W",
  "YTT",
]
ignore = [
  "E501",
  "S311",
  "S603",
]
